name: Moodle Plugin Release

on:
  release:
    types: [published]

jobs:
  publish-release-on-moodle:
    name: "Publish new release in Moodle plugins directory"
    uses: learnweb/moodle-workflows-learnweb/.github/workflows/moodle-release.yml@main
    with:
      plugin-name: 'mod_groupmembers'
    secrets: inherit
